# Generated by Django 5.1.4 on 2024-12-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(choices=[('Operations', 'Operations'), ('Strategy', 'Strategy'), ('Credit', 'Credit'), ('Human Resource', 'Human Resource'), ('Sales', 'Sales'), ('Finance', 'Finance'), ('Communictions and Marketing', 'Communications and Marketing'), ('Internal control and compliance', 'Internal control and compliance'), ('Facility', 'Facility')], max_length=50, null=True)),
                ('picture', models.ImageField(upload_to='Pictures')),
            ],
        ),
    ]
