# Generated by Django 5.1.4 on 2025-01-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Operations', 'Operations'), ('Strategy', 'Strategy'), ('Credit', 'Credit'), ('Human Resource', 'Human Resource'), ('Sales', 'Sales'), ('Finance', 'Finance'), ('Communications and Marketing', 'Communications and Marketing'), ('R.C.C', 'R.C.C')], default='Operations', max_length=50),
        ),
    ]
