# Generated by Django 5.1.4 on 2024-12-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('product_description', models.CharField(max_length=200, null=True)),
                ('product_quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('Stationary', 'Stationary'), ('Office Equipment', 'Office Equipment'), ('Clothes', 'Clothes')], max_length=50, null=True)),
            ],
        ),
    ]
