# Generated by Django 5.1.4 on 2025-01-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_on',
            new_name='updated_at',
        ),
    ]
